repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.24
    hooks:
      # Update the uv lockfile
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.11
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  #- repo: https://github.com/pre-commit/mirrors-mypy
    #rev: ''  # Use the sha / tag you want to point at
    #hooks:
    #- id: mypy
      #additional_dependencies:
      #- types-atomicwrites
      #- types-tabulate
      #- types-freezegun
      #- types-pytz
      #- types-python-dateutil
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./.venv/bin/pytest tests
        language: python
        pass_filenames: false
        always_run: true